name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests (optional)
        run: echo "No tests yet" # ou npm test si tu as vraiment un fichier test

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --project=0479cc01-2a03-49f5-97bb-b64f199a744d
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
